### ISSUE TITLE
Migration issues on Oracle DB with Textfield that has an index

### ISSUE THREAD

**Issue by ProfMerlin** [praekelt/jmbo#40]
Migrations on Oracle db fail because Oracle does not accept an index on a Text field:
https://github.com/praekelt/jmbo/blob/feature/django-1.9/jmbo/migrations/0001_initial.py#L55

**Comment by hedleyroos** [comment]
I'm going to completely remove db index from the description field. It doesn't scale well and a proper search backend yields better results.
