### ISSUE TITLE
Timezone awareness

### ISSUE THREAD

**Issue by Rizziepit** [praekelt/jmbo#9]
We are going to keep running into problems with mixing timezone aware and naive datetime objects. Django makes naive model fields aware when it loads them from the database. However, any arithmetic or comparison done with a naive datetime,  for instance ```retract_on <= datetime.now()```, will raise an exception. It should be replaced with ```retract_on <= timezone.now()```. This is easy to fix in jmbo but what about dependent apps?

Another important factor is that when timezone support is active (```USE_TZ``` in settings.py), Django is going to automatically create timezone aware datetimes in forms.

**Comment by hedleyroos** [comment]
Everything is now TZ aware in Jmbo 2.
